### ISSUE TITLE
Plantear idea de proyecto.

### ISSUE THREAD

**Issue by jcamilobm** [JAGamarra/proyecto_ciclo3_misiontic2022#2]

**Comment by JAGamarra** [comment]
> Por favor editar sólo este comentario para organizar el **planteamiento del problema.**

# Planteamiento del proyecto

Sitio web de renta de vehiculos automotores, con dos tipos de usuario (administrador o propietario, y cliente).

...

**Comment by JAGamarra** [comment]
> Por favor editar sólo este comentario para organizar la **lista de historias de usuario sin priorizar**

# lista de historias de usuario sin priorizar

 > Formato para cada historia: _Yo como_  ...   _quiero_    ...    _para_   ...


1. Yo como usuario quiero ver los carros disponibles para elegir alguno y comenzar el proceso de reserva.
2. Yo como usuario quiero ver un resumen de la compra para verificar el proceso de compra.
3. Yo como usuario quiero registrarme e inciar sesión para consultar o modificar la reserva 24h antes de la fecha establecida.

4. Yo como administrador quiero  modificar el catálogo de vehículos  para  agregar/editar/eliminar  vehículos u oficinas.


---
 **Lluvia de Ideas:**

Cliente -> (*Puede sufrir modificaciones)
 1. Puede alquilar o reservar un vehiculo.
 2. Puede cancelar una reserva cierto tiempo antes de la fecha establecida.
 3. Puede pagar el alquiler(pago físico o pago electrónico).
 4. Puede ver el listado o catalogo de vehiculos disponibles.
 5. Puede iniciar sesión
 6. Puede registrarse


--- moví comentario de Eliana

(Cliente posibles funcionalidades)
1. Puede registrarse
2. Puede iniciar sesión
3. Puede ver el listado o catálogo de vehículos disponibles.
4. Puede ver las oficinas de retiro y entrega de vehículos.
5. Puede alquilar o reservar un vehículo.
6. Puede cancelar una reserva 24 horas antes de la reserva, de lo contrario tendrá una penalidad de un porcentaje sobre el valor de la renta.
7. Pagar el alquiler pago electrónico (generalmente estas empresas siempre solicitan tarjeta de crédito para la reserva)
8. Sugiero que los usuarios solo pueden tener una reserva activa

(Administrador posibles funcionalidades)
1. Puede iniciar sesión.
2. Puede registrar usuarios.
3. Puede agregar o eliminar vehículos del catálogo.
4. Puede agregar o eliminar las oficinas de retiro y entrega de vehículos.
5. Puede cancelar reservas.
6. Puede modificar los precios de alquiler de los vehículos.

(La metodología para la reserva del carro sería)
1. Elegir oficina de retiro y oficina de entrega de vehículo.
2. Elegir hora de retiro y hora de entrega del vehículo.
3. Elegir uno de los vehículos disponibles.
4. Visualizar las características y beneficios del vehículo.
5. Visualizar resumen de la reserva.
6. Legalizar reserva.
6. Iniciar la sesión o registrarse.
7. Realizar pago.
8. Visualizar información de la reserva para retirar el vehículo.

Estas páginas me parecieron interesantes para ir creando las funcionalidades:
https://www.alamo.com/es/inicio.html
https://lac.thrifty.com/
https://www.budgetlac.com/

----
Registro de usuarios
El formulario debe contener los siguientes datos:
1. Nombres completos.
2. Tipo de documento.
3. Número de documento.
4. Correo electrónico.
5. Fecha de nacimiento.
6. Número de contacto.
7. Contraseña

Inicio de sesión
El formulario debe contener los siguientes datos:
1. Correo electrónico.
2. Contraseña.
3. Opción para recuperar contraseña.

Catálogo de vehículos
Tipo de vehículo
Características
precio por día

Oficinas de entrega y retiro
Nombre de la oficina
Horario de atención
Dirección

**Comment by jcamilobm** [comment]
# Historias de usuario priorizadas

> Responsabilidad: Product owner

**Criterios**

- priority : low , medium y high   . 

| Historia  ID | product owner | 
| --- | --- | 
| 1 | priority : high |
| 2 | priority :medium | 
| 3 | priority :low  | 
| 4 |  priority :5  |
| 5 | priority :5  |
| 6 |  priority :5  | 
| 7 |  priority :5  |
| 8 | priority :5  | 
| 9 |  priority :5  | 
| 10 |  priority :5  |

**Comment by Evacca** [comment]
# Historias de usuario priorizadas:

1.
2.
3.
4.
5.
6.
7.
8.
9.
10.

**Comment by Evacca** [comment]
# Detalles de cada historia de usuario

**1.**

ID:
Nombre:
Prioridad en negocio:
Iteración asignada:
rol: 
funcionalidad:
Criterios de aceptación:
* ...
* …

---

**2.**

ID:
Nombre:
Prioridad en negocio:
Iteración asignada:
rol: 
funcionalidad:
Criterios de aceptación:
* ...
* …

**3.**

ID:
Nombre:
Prioridad en negocio:
Iteración asignada:
rol: 
funcionalidad:
Criterios de aceptación:
* ...
* …

**Comment by jcamilobm** [comment]
# Planeación.

**Objetivo:** Estimar el puntaje de cada historia de usuario ya priorizada.

**criterio de votación:** Serie de Fibonacci teniendo en cuenta un pivote. 

# Planning poker

La estimación de los **Story Points** se puede hacer con un **planning poker**, el procedimeinto es:

1. Cada desarrollador estima de forma anónima los esfuerzos con valores de su baraja.
2. Se revelan las cartas.
3. Debate para lograr consenso.

* Podemos realizar la votación en [planning poker](https://planningpokeronline.com/)
---

> En la siguiente tabla se rescantan los resultados del planning poker.

| Historia  ID | Camilo | Julián | Eliana | Natalia | Estimation |
| --- | --- | --- | --- | --- | --- |
| 1 | point:1 , priority :5  | point:1 , priority :5 | point:1 , priority :5 | point:1 , priority :5 |  ... |
| 2 | point:1 , priority :5  | point:1 , priority :5 | point:1 , priority :5 | point:1 , priority :5 |  ... |
| 3 | point:1 , priority :5  | point:1 , priority :5 | point:1 , priority :5 | point:1 , priority :5 |  ... |
| 4 | point:1 , priority :5  | point:1 , priority :5 | point:1 , priority :5 | point:1 , priority :5 |  ... |
| 5 | point:1 , priority :5  | point:1 , priority :5 | point:1 , priority :5 | point:1 , priority :5 |  ... |
| 6 | point:1 , priority :5  | point:1 , priority :5 | point:1 , priority :5 | point:1 , priority :5 |  ... |
| 7 | point:1 , priority :5  | point:1 , priority :5 | point:1 , priority :5 | point:1 , priority :5 |  ... |
| 8 | point:1 , priority :5  | point:1 , priority :5 | point:1 , priority :5 | point:1 , priority :5 |  ... |
| 9 | point:1 , priority :5  | point:1 , priority :5 | point:1 , priority :5 | point:1 , priority :5 |  ... |
| 10 | point:1 , priority :5  | point:1 , priority :5 | point:1 , priority :5 | point:1 , priority :5 |  ... |

**Comment by jcamilobm** [comment]
# Seleccionar historias de usuario a desarrollar en el sprint 1

*  Teniendo en cuenta la prioridad y la cantidad de puntos que se cree alcanzable para el sprint 1.
*  Las tareas elegidas pasan al TO DO del tablero (Sprint Backlog)

## Historias de usuario elegidas para el sprint 1

* ...
*  ...
